name: Rust toolchain setup

on: [push, pull_request, workflow_dispatch]

permissions: {}

jobs:
  setup:
    name: Effect of setting up Rust

    runs-on: macos-latest

    steps:
    - name: Bash version before Rust setup
      run: bash --version

    - name: Set up Rust toolchain
      uses: actions-rust-lang/setup-rust-toolchain@v1

    - name: Bash version after Rust setup
      run: bash --version
